version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: multipart
    versions:
    - "> 0.1"
  - dependency-name: redis
    versions:
    - "< 2.10.7, >= 2.10.6.a"
  - dependency-name: yapf
    versions:
    - ">= 0.26.a, < 0.27"
  - dependency-name: responses
    versions:
    - 0.13.1
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: cryptography
    versions:
    - 3.4.1
  - dependency-name: coverage
    versions:
    - "5.4"
