os: osx
language: generic
osx_image: xcode8.3
matrix:
  include:
    - env:
        - PYTHON_MAJOR="py34|py35"
        - PYTHON_VERSION="3.5.5 3.4.8"
    - env:
        - PYTHON_MAJOR="py36|py37"
        - PYTHON_VERSION="3.6.5 3.7.0"
    - env:
        - PYTHON_MAJOR=py2
        - PYTHON_VERSION="2.7.14"
    - env:
        - PYTHON_MAJOR=pypy
        - PYTHON_VERSION="pypy2.7-5.10.0"
cache:
  directories:
    - $HOME/.pyenv
after_script: set +e
install:
  - source travis/install.sh
script:
  - source travis/script.sh
after_success:
  - pip install codecov
  - codecov
notifications:
  email: false
  slack:
    secure: A2AVwYqUoh2hza7eQ2yl5CNWEI6ozLZGolyh1U1Iez4t/lKD9+Y1FrcmsEjYoTYy0B2Q55RHxNZoSq5tVGb5Ap1f/bRakAWOmiedja5obYzIUqI+lJPXZBvxdlobOzuYUxRZOFCMndkN6UAzdJx2gaVdtj4iH/DxoVL6wK2wlfA=
  webhooks: https://www.travisbuddy.com/
branches:
  except:
    # Used by bors
    - trying.tmp
    - staging.tmp
